name: driver_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.1
  sizer: ^3.0.5
  country_picker: ^2.0.27
  font_awesome_flutter: ^10.8.0
  pin_code_fields: ^8.0.1
  persistent_bottom_nav_bar: ^6.2.1
  firebase_auth: ^5.6.2
  page_transition: ^2.2.1
  provider: ^6.1.5
  recaptcha_enterprise_flutter: ^18.7.1
  firebase_app_check: ^0.3.2+9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/categories/
    - assets/images/splashScreenImage/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: UberMoveMedium
      fonts:
        - asset: assets/fonts/UberMoveMedium.otf

    - family: UberMoveBold
      fonts:
        - asset: assets/fonts/UberMoveBold.otf